CREATE TABLE IF NOT EXISTS orders (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  city TEXT NOT NULL,
  status TEXT DEFAULT 'جديد' NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
